export const EXISTING_EMAIL_ERR = "Пользователь с таким email уже существует.";
export const AUTH_ERR = "При регистрации пользователя произошла ошибка.";
export const UPDATE_PROFILE_ERR = "При обновлении профиля произошла ошибка.";
export const SERVER_ERR = "Произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз";
export const BREAKPOINT = 1024;
export const WINDOWWIDTH = window.innerWidth;
export const KEY_WORDS_ERR = "Нужно ввести ключевое слово.";
export const DATA_NOT_CHANGED_ERR = "Данные пользователя не были изменены.";
export const EMAIL_REGEX = "^\\S+@\\S+\\.\\S+$"